from eda import record_column,type_column,pre_RR0_column,post_RR0_column


print(record_column.record_des)
print('##'*20)
print(record_column.record_skew)
print('##'*20)
print(record_column.record_corr)
print('##'*20)
print(record_column.record_std)
print('##'*20)
print(type_column.type_count)
print('##'*20)
print('0_pre-RR description :',pre_RR0_column.pre_RR0_des)
print('##'*20)
print('0_pre-RR Null values :',pre_RR0_column.pre_RR0_null)
print('##'*20)
print('0_pre-RR Skewness :',pre_RR0_column.pre_RR0_skewness)
print('##'*20)
print('0_pre-RR Variance :',pre_RR0_column.pre_RR0_var)
print('##'*20)
print('0_pre-RR Standard Deviation :',pre_RR0_column.pre_RR0_std)
print('##'*20)
print('0_pre-RR Covariance :',pre_RR0_column.pre_RR0_cov)
print('##'*20)
print('0_pre-RR Correlation :',pre_RR0_column.pre_RR0_corr)
print('##'*20)
print('0_post-RR description :',post_RR0_column.post_RR0_des)
print('##'*20)
print('0_post-RR Null values :',post_RR0_column.post_RR0_null)
print('##'*20)
print('0_post-RR Skewness :',post_RR0_column.post_RR0_skewness)
print('##'*20)
print('0_post-RR Variance :',post_RR0_column.post_RR0_var)
print('##'*20)
print('0_post-RR Standard Deviation :',post_RR0_column.post_RR0_std)
print('##'*20)
